apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ks-bot

resources:
- ../../base

images:
- name: ghcr.io/eunchurn/discord-bot-kates-whip
  newName: ghcr.io/eunchurn/discord-bot-kates-whip
  newTag: sha-8cb452d
