apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kates-whip-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: openebs-rwx-fiserver
  resources:
    requests:
      storage: 1Gi
